# Full configuration: https://github.com/eko/FeedBundle
eko_feed:
  feeds:
    users:
      title:       'Slave - Shoko Cosplay'
      description: 'Slave - Shoko Cosplay'
      link:        'https:///slave.shoko-cosplay.fr'
      encoding:    'utf-8'
      author:      'Shoko Cosplay' # Only required for Atom feeds
