# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "imagick"
  loaders:
    stream.avatars:
      stream:
        wrapper: gaufrette://
  resolvers:
    aws_s3_resolver:
      aws_s3:
        client_config:
          credentials:
            key: "%env(MINIO_PUBLIC_KEY)%"
            secret: "%env(MINIO_SECRET_KEY)%"
          region: "us-east-1"
          endpoint: "%env(MINIO_SERVER)%"
          use_path_style_endpoint: true
        bucket: 'slave-shoko-cosplay'
        get_options:
          scheme: http
        cache_prefix: 'storage/'
        put_options:
          CacheControl: "max-age=86400"
          ACL: "public-read"
  data_loader: default
  controller:
    redirect_response_code: 302
  twig:
    mode: lazy
  webp:
    generate:    true
  cache: aws_s3_resolver
  filter_sets:
    webp:
      format: webp
      quality: 85
      post_processors:
        optipng:
          strip_all: true
          level: 3
    og_image:
      format: webp
      quality: 85
      filters:
        thumbnail: { size: [ 1200, 630 ], mode: inset }
      post_processors:
        optipng:
          strip_all: true
          level: 3
    twitter_card:
      format: webp
      quality: 85
      filters:
        thumbnail: { size: [ 1200, 600 ], mode: inset }
      post_processors:
        optipng:
          strip_all: true
          level: 3
