# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
  adapters:
    s3_adapter:
      awss3v3:
        client: 'amazonS3'
        bucket: 'shoko-cosplay'

  filesystems:
    s3_filesystem:
      adapter: 's3_adapter'
