framework:
  validation:

vich_uploader:
  db_driver: orm
  storage: gaufrette
  mappings:
    avatars:
      uri_prefix: 'avatars'
      upload_destination: storage_avatar_fs
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
