services:
  phptest:
    image: ghcr.io/shoko-cosplay/sc-bondage-docker:master
    volumes:
      - .:/var/www:delegated
    links:
      - dbtest
      - redistest
      - vaulttest
      - mailtest
    networks:
      - test
    environment:
      REDIS_HOST: redistest
      DATABASE_URL: postgresql://test:test@dbtest:5432/test?serverVersion=12&charset=utf8
  mailtest:
    image: mailhog/mailhog
    ports:
      - 1080:8025
  redistest:
    restart: unless-stopped
    image: redis:7-alpine
    networks:
      - test
  dbtest:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - 5433:5432
    networks:
      - test
  vaulttest:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"
networks:
  test:
